CREATE TABLE ACG_Character.Profile
(
ID 			INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Actor		VARCHAR(30),
Product		VARCHAR(30),
Media_1 	BLOB(10M),
ref_1 		VARCHAR(100),
details_1 	VARCHAR(100),
Media_2 	BLOB(10M),
ref_2 		VARCHAR(100),
details_2 	VARCHAR(100),
PRIMARY KEY (ID)
);